[theme]
# Primary accent color for interactive elements 
#primaryColor = "#9fc5e8"

# Background color for the main content area 
#backgroundColor = "#3f4f53"

# Background color used for the sidebar and most interactive widgets
#secondaryBackgroundColor = "#586e75"

# Color used for almost all text
textColor = "#fff"